### ISSUE TITLE
A playable BlackJack

### ISSUE THREAD

**Issue by Scrivener07** [Scrivener07/FO4_Games#13]
We need a playable black jack game.
- [x] Issue #9 Simple AI for dealer and opponent players.
- [ ] Issue #5 How to handle game mode?
- [ ] Issue #11 Create a bound presentation for the gambling table.
- [ ] Issue #17 Wager a simple bet with caps.

**Comment by TheWhiteCollarPlayers** [comment]
Agreed, here are what I believe are a good set of basic goals to get out an Alpha Build:

-Activator table placed in a single predetermined location in the Commonwealth, perhaps the Colonial Taproom in Diamond City? (The fancy bar in the upper stands)

-Simple wager method for the player, selecting an option to bet X caps works.

-Competing against at least just the dealer. If other player AI is already mostly complete then great too.

These are the only items I would consider necessary for a "first playable build" everything past these seems to get into features/enhancements in my opinion. Would love to hear other thoughts on this.

**Comment by TheWhiteCollarPlayers** [comment]
We have a solid plan for how to implement Blackjack and future games as well, closing this issue as the info here is no longer needed!
